import React, { useEffect, useState } from 'react';
import type { Member, UserRole } from '../types';
import { fetchSaccoJson, postSaccoJson } from '../lib/api';

type LoanRow = { id:string; member_name:string; principal_amount:number; interest_rate:number; status:string; member_savings:number; membership_days:number; secretary_notes?:string; treasurer_notes?:string; due_date?:string };
type Policy = { default_interest_rate:number; maximum_principal:number|null; minimum_savings:number; minimum_membership_days:number; require_active_membership:boolean };

export default function LoansView({ role, token, members }: { role: UserRole; token: string; members: Member[] }) {
  const [loans,setLoans]=useState<LoanRow[]>([]); const [policy,setPolicy]=useState<Policy|null>(null);
  const [notice,setNotice]=useState(''); const [error,setError]=useState('');
  const [memberId,setMemberId]=useState(''); const [principal,setPrincipal]=useState(''); const [dueDate,setDueDate]=useState(''); const [applicationNotes,setApplicationNotes]=useState('');
  const load=async()=>{ const [l,p]=await Promise.all([fetchSaccoJson<LoanRow[]>('/api/loans',{},token),fetchSaccoJson<Policy>('/api/loans-policy',{},token)]); setLoans(l);setPolicy(p); };
  useEffect(()=>{void load().catch(e=>setError(e.message));},[token]);
  const act=async(url:string,payload:unknown)=>{setError('');setNotice('');try{await postSaccoJson(url,payload,token);await load();setNotice('Loan workflow updated.');}catch(e){setError(e instanceof Error?e.message:'Action failed.');}};
  const savePolicy=async(e:React.FormEvent)=>{e.preventDefault();if(!policy)return;setError('');try{await fetchSaccoJson('/api/loans-policy',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({defaultInterestRate:Number(policy.default_interest_rate),maximumPrincipal:policy.maximum_principal,minimumSavings:Number(policy.minimum_savings),minimumMembershipDays:Number(policy.minimum_membership_days),requireActiveMembership:policy.require_active_membership})},token);setNotice('Loan policy saved.');await load();}catch(err){setError(err instanceof Error?err.message:'Policy could not be saved.');}};
  const addMemberLoan=async(e:React.FormEvent)=>{e.preventDefault();setError('');setNotice('');try{await postSaccoJson('/api/loans',{memberId,principalAmount:Number(principal),dueDate,notes:applicationNotes},token);setMemberId('');setPrincipal('');setDueDate('');setApplicationNotes('');await load();setNotice('Loan request added for the member and sent to the Secretary for review.');}catch(err){setError(err instanceof Error?err.message:'Loan request could not be added.');}};
  const notes=()=>window.prompt('Review notes (recommended):')||'';
  return <main className="flex-1 overflow-y-auto bg-slate-50 p-4 sm:p-8"><div className="mx-auto max-w-6xl space-y-6">
    <header><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Controlled credit workflow</p><h1 className="mt-1 text-2xl font-black text-slate-900">Loan applications</h1><p className="mt-2 text-sm text-slate-500">Secretary eligibility → Treasurer figures → Chairman final decision.</p></header>
    {role==='Chairman'&&<form onSubmit={addMemberLoan} className="rounded-2xl border border-emerald-200 bg-white p-5"><h2 className="font-bold text-slate-900">Add loan for a registered member</h2><p className="mt-1 text-xs text-slate-500">This records the request on the member’s behalf. The Chairman’s current interest rate is applied by the server and the request begins with Secretary review.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><select value={memberId} onChange={e=>setMemberId(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm" required><option value="">Select active member</option>{members.filter(member=>member.status==='Active').map(member=><option key={member.id} value={member.id}>{member.name} · ID {member.idNumber}</option>)}</select><input type="number" min="1" step="0.01" value={principal} onChange={e=>setPrincipal(e.target.value)} placeholder="Principal amount (KES)" className="rounded-xl border px-3 py-2.5 text-sm" required/><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm"/><input value={applicationNotes} onChange={e=>setApplicationNotes(e.target.value)} placeholder="Purpose or approval reference" className="rounded-xl border px-3 py-2.5 text-sm"/></div><button className="mt-4 rounded-xl bg-emerald-700 px-4 py-2.5 text-xs font-bold text-white">Add loan request</button></form>}
    {role==='Chairman'&&policy&&<form onSubmit={savePolicy} className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Chairman loan policy</h2><div className="mt-4 grid gap-4 sm:grid-cols-4">{[['Interest rate %','default_interest_rate'],['Maximum principal','maximum_principal'],['Minimum savings','minimum_savings'],['Minimum membership days','minimum_membership_days']].map(([label,key])=><label key={key} className="text-xs font-bold text-slate-600">{label}<input type="number" min="0" step={key==='default_interest_rate'?'.001':'1'} value={(policy as any)[key]??''} onChange={e=>setPolicy({...policy,[key]:e.target.value===''?null:Number(e.target.value)})} className="mt-2 w-full rounded-xl border px-3 py-2.5" /></label>)}</div><button className="mt-4 rounded-xl bg-emerald-600 px-4 py-2.5 text-xs font-bold text-white">Save policy</button></form>}
    {(error||notice)&&<p className={`rounded-xl p-3 text-sm ${error?'bg-rose-50 text-rose-700':'bg-emerald-50 text-emerald-700'}`}>{error||notice}</p>}
    <section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Member</th><th>Request</th><th>Savings</th><th>Days</th><th>Rate</th><th>Stage</th><th className="p-4">Action</th></tr></thead><tbody className="divide-y">{loans.map(l=><tr key={l.id}><td className="p-4 font-bold">{l.member_name}</td><td>KES {Number(l.principal_amount).toLocaleString()}</td><td>KES {Number(l.member_savings).toLocaleString()}</td><td>{l.membership_days}</td><td>{l.interest_rate}%</td><td><span className="rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-800">{l.status}</span></td><td className="p-4">{l.status==='SecretaryReview'&&role==='Secretary'&&<div className="flex gap-2"><button onClick={()=>void act(`/api/loans/${l.id}/secretary-review`,{eligible:true,notes:notes()})} className="text-xs font-bold text-emerald-700">Eligible</button><button onClick={()=>void act(`/api/loans/${l.id}/secretary-review`,{eligible:false,notes:notes()})} className="text-xs font-bold text-rose-700">Reject</button></div>}{l.status==='TreasurerReview'&&role==='Treasurer'&&<div className="flex gap-2"><button onClick={()=>void act(`/api/loans/${l.id}/treasurer-review`,{approved:true,notes:notes()})} className="text-xs font-bold text-emerald-700">Figures correct</button><button onClick={()=>void act(`/api/loans/${l.id}/treasurer-review`,{approved:false,notes:notes()})} className="text-xs font-bold text-rose-700">Reject</button></div>}{l.status==='ChairmanReview'&&role==='Chairman'&&<div className="flex gap-2"><button onClick={()=>void act(`/api/loans/${l.id}/approve`,{})} className="text-xs font-bold text-emerald-700">Final approve</button><button onClick={()=>void act(`/api/loans/${l.id}/reject`,{reason:notes()})} className="text-xs font-bold text-rose-700">Reject</button></div>}</td></tr>)}{!loans.length&&<tr><td colSpan={7} className="p-8 text-center text-slate-500">No loan applications yet.</td></tr>}</tbody></table></section>
  </div></main>;
}
