import React from 'react';
import { BookOpenCheck, CheckCircle2, ShieldCheck } from 'lucide-react';

const roles = [
  ['Chairman', 'Governance and final accountability', 'Creates and resets accounts, removes a settled member and their login account, manages loan policy, gives final loan decisions, closes completed months, and has full operational access. Financial history remains retained when a member is removed.'],
  ['Secretary', 'Day-to-day operations and loan eligibility', 'Posts and corrects daily collections, expenses and journal records; registers members and vehicles; assigns drivers; views reports; and completes the first loan eligibility review. The Secretary cannot reconcile bank payments, manage accounts, make the final loan decision, or close a month. Only for a verified pending Chairman recovery request, the Secretary may issue that Chairman a temporary recovery password.'],
  ['Treasurer', 'Financial review and reconciliation', 'Posts financial entries, reconciles payments, reviews loan figures, and records authorised repayments. The Treasurer cannot register members or make the final loan decision.'],
  ['Accountant', 'Day-to-day ledger management', 'Posts, corrects, and reverses ledger entries; reconciles payments; and prepares internal reports. The Accountant cannot review/approve loans or manage user accounts.'],
  ['Auditor', 'Independent read-only oversight', 'Can inspect records, loans, payments, and reports but cannot create, edit, reconcile, approve, reset passwords, or close a month.'],
  ['Member', 'Personal self-service', 'Can see only their own profile, vehicle, receipts, payments, loans, settings, and loan rejection reasons; they may submit or reapply for their own loan.']
];

export default function RoleGuideView() {
  return <main className="flex-1 overflow-y-auto bg-slate-50 p-4 sm:p-8"><div className="mx-auto max-w-5xl space-y-6"><header className="rounded-3xl bg-gradient-to-br from-slate-950 to-emerald-900 p-6 text-white sm:p-8"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-emerald-200"><BookOpenCheck className="h-4 w-4" /> Clear responsibilities</p><h1 className="mt-3 text-3xl font-black">Officer roles and access</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-emerald-50">The system enforces these permissions on the server. Navigation helps people find their work, but it never grants extra access.</p></header><section className="grid gap-4 md:grid-cols-2">{roles.map(([role, focus, description]) => <article key={role} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><span className="rounded-xl bg-emerald-50 p-2 text-emerald-700"><ShieldCheck className="h-5 w-5" /></span><div><h2 className="font-black text-slate-900">{role}</h2><p className="mt-1 text-xs font-bold uppercase tracking-wider text-emerald-700">{focus}</p></div></div><p className="mt-4 text-sm leading-6 text-slate-600">{description}</p></article>)}</section><section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-amber-700" /><div><h2 className="font-black text-amber-950">Loan decision sequence</h2><p className="mt-2 text-sm leading-6 text-amber-900">Member application → Secretary eligibility review → Treasurer financial review → Chairman final decision. A rejection always needs a clear reason; the member sees it and can reapply when the issue is corrected.</p></div></div></section><section className="rounded-2xl border border-sky-200 bg-sky-50 p-5"><div className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-sky-700" /><div><h2 className="font-black text-sky-950">Chairman recovery exception</h2><p className="mt-2 text-sm leading-6 text-sky-900">Only the Secretary can review a pending Chairman recovery request and issue that Chairman a 24-hour temporary recovery password after identity verification. This does not give the Secretary authority to reset members or other officers.</p></div></div></section></div></main>;
}
